-
  branches:
    only:
      - main

  image: Visual Studio 2022
  version: 0.1.2-master-build.{build}
  configuration: Release

  before_build:
    - dotnet restore

  build:
    verbosity: minimal

  artifacts:
    - path: 'src\AvaloniaHex\bin\Release\*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: orcP0C1iuBVKxnv/uAUehgU1KEI/lCpbSxDqbckd3sZ7XxcuENj6PrExs6SdJIf1
    skip_symbols: false
    artifact: /.*\.nupkg/